In [2]:
import numpy as np
np.random.seed(0)  # 재현 가능성을 위한 시드 값

x1 = np.random.randint(10, size=6)  # 1차원 배열
x2 = np.random.randint(10, size=(3, 4))  # 2차원 배열
x3 = np.random.randint(10, size=(3, 4, 5))  # 3차원 배열


In [3]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)


x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [4]:
print(3)

3


In [6]:
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

dtype: int32
itemsize: 4 bytes
nbytes: 240 bytes


In [7]:
x1

array([5, 0, 3, 3, 7, 9])

In [8]:
x1[0]

5

In [9]:
x1[4]

7

In [10]:
x1[-1]

9

In [11]:
x1[-2]

7

In [12]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [13]:
x2[2,0]

1

In [14]:
x2[2,-1]

7

In [15]:
x2[0,0]=12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [16]:
x1[0] = 3.14159
x1 #소수점 이하는 잘림 array 타입이 int이기 때문

array([3, 0, 3, 3, 7, 9])

In [17]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x[:5]

array([0, 1, 2, 3, 4])

In [19]:
x[5:]

array([5, 6, 7, 8, 9])

In [20]:
x[4:7]

array([4, 5, 6])

In [21]:
x[::2]

array([0, 2, 4, 6, 8])

In [22]:
x[1::2]

array([1, 3, 5, 7, 9])

In [23]:
x[::-1] # 모든 요소들을 거꾸로 나열

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [24]:
x[5::-2]

array([5, 3, 1])

In [25]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [26]:
x2[:2, :3] #2개행 3개열

array([[12,  5,  2],
       [ 7,  6,  8]])

In [27]:
x2[:3, ::2] #모든행, 한 열 걸러 하나 씩

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [29]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [32]:
x2[:,:3]

array([[12,  5,  2],
       [ 7,  6,  8],
       [ 1,  6,  7]])

In [33]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [34]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [35]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [36]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [38]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [40]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [41]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [43]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
x = np.array([1, 2, 3])

x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [45]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [46]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [48]:
print(np.arange(1,10).reshape((2,4)))

ValueError: cannot reshape array of size 9 into shape (2,4)

In [49]:
x[:2, np.newaxis]

array([[1],
       [2]])

In [50]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [51]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [52]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [53]:
# 첫 번째 축을 따라 연결
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [58]:
# 두 번째 축을 따라 연결(0부터 시작되는 인덱스 방식) 
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [64]:
kk = np.arange(1,9).reshape((2,2,2))
np.concatenate([kk, kk], axis=2)

array([[[1, 2, 1, 2],
        [3, 4, 3, 4]],

       [[5, 6, 5, 6],
        [7, 8, 7, 8]]])

In [65]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], [6, 5, 4]])

# 배열을 수직으로 쌓음
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [66]:
# 배열을 수평적으로 쌓음
y = np.array([[99], [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [74]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [68]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [82]:
upper, lower = np.vsplit(grid, [
    2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [70]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [77]:
upper, lower = np.vsplit(grid, [1])
print(upper)
print(lower)

[[0 1 2 3]]
[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
